title: Blog From Inside The Matrix
author: Mathusan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog contains everything I am interested in and what I enjoy.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  The-M8rix # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
